---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: simple-deployment-old-foreman
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-users]"
    - "recipe[envbuilder]"
    - "recipe[odi-nginx]"
    - "recipe[odi-simple-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      odi-ruby:
        users:
          deploytest:
          - '2.1.2'
      envbuilder:
        base_dir: "/home/env"
        base_dbi: "production"
        owner: "env"
        group: "env"
      project_fqdn: "deploytest.theodi.org"
      git_project: "deployment-test-app"
      RACK_ENV: "production"
      deploy:
        revision: "master"
  - name: simple-deployment-new-foreman
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-users]"
    - "recipe[envbuilder]"
    - "recipe[odi-nginx]"
    - "recipe[odi-simple-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      odi-ruby:
        users:
          deploytest:
          - '2.1.2'
      envbuilder:
        base_dir: "/home/env"
        base_dbi: "production"
        owner: "env"
        group: "env"
      project_fqdn: "deploytest.theodi.org"
      git_project: "deployment-test-app"
      RACK_ENV: "production"
      deploy:
        revision: "new-upstart"
