language: ruby
rvm:
- 2.1.1
env:
  global:
  - secure: eFEQDAEq7wbVR+dblHm2dCU878JxhzyASWL8ufQQZpkFUDjTq0D0Y+VBJdhSX0rTuptzzfoSaLoHKZ3558B/B8qUlSCMpQfHuomMbHC2JYIfqm6RL6QN0CUvxBLBniTbyMHLNowWU0n2NzgE31bBrjf8rlik8mPJZ1YLW2skjKg=
  - secure: Mm3fKBvV460w8cWjHcf550AS+/Vc/LgmzNkPZf1Wgs25YK0C6VdxH7nlPYu67DutIWyypkX7VKAreZZc0KMeMeQw3jlvj9j8WkwrBK27FuXvZvGMcSeAcSgXigDb300otTdRVqCTANTHHd7cPEi8V0PWypkASl+RAcxXrMcoV3o=
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: CndFEb9N8DZNPXyT5OFN2iR9QRzUlowOA7VbgVdZ85zRIJ3KKin6wVnBpdveVygCetOK8pfZ7zUGYrKlUUaoTei4s29+EYhpGGVJGzm4jtwxN9lPHwla06xEKjzYVFsWH9Vmiu5LsAjSp3ch0ypzJp7v/ItsyRO7KPtUubWAST4=
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
script:
- KITCHEN_INSTANCE=simple-deployment-old-foreman travis_wait 60 bundle exec rake kitchen:test
- KITCHEN_INSTANCE=simple-deployment-new-foreman travis_wait 60 bundle exec rake kitchen:test
after_success:
- openssl enc -d -aes-256-cbc -k $CHEF_KEY -in deploy/key.enc -out deploy/key.pem
- chmod 600 deploy/key.pem
- bundle exec berks install
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false"] && bundle exec rake berkshelf:upload'
