language: ruby
rvm:
- 2.1.1
env:
  global:
  - secure: eFEQDAEq7wbVR+dblHm2dCU878JxhzyASWL8ufQQZpkFUDjTq0D0Y+VBJdhSX0rTuptzzfoSaLoHKZ3558B/B8qUlSCMpQfHuomMbHC2JYIfqm6RL6QN0CUvxBLBniTbyMHLNowWU0n2NzgE31bBrjf8rlik8mPJZ1YLW2skjKg=
  - secure: Mm3fKBvV460w8cWjHcf550AS+/Vc/LgmzNkPZf1Wgs25YK0C6VdxH7nlPYu67DutIWyypkX7VKAreZZc0KMeMeQw3jlvj9j8WkwrBK27FuXvZvGMcSeAcSgXigDb300otTdRVqCTANTHHd7cPEi8V0PWypkASl+RAcxXrMcoV3o=
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: CndFEb9N8DZNPXyT5OFN2iR9QRzUlowOA7VbgVdZ85zRIJ3KKin6wVnBpdveVygCetOK8pfZ7zUGYrKlUUaoTei4s29+EYhpGGVJGzm4jtwxN9lPHwla06xEKjzYVFsWH9Vmiu5LsAjSp3ch0ypzJp7v/ItsyRO7KPtUubWAST4=
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''

script:
- travis_wait 50 bundle exec rake kitchen:test
